Console.WriteLine(" There are 28 cats at an animal shelter. The percentage of male cats is .54, or 54% and the percentage of female cats is .46, or 46%. How many cats are male and female?");
double malecats;
malecats = .6;
double femalecats;
femalecats = .4;
int allcats;
allcats = 28;
int numberofmalecats;
numberofmalecats = (int)(malecats * allcats);
int numberoffemalecats;
numberoffemalecats = (int)(femalecats * allcats);
Console.WriteLine();
Console.WriteLine(numberofmalecats + " male cats");
Console.WriteLine();
Console.WriteLine(numberoffemalecats + " female cats");